---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: 
manual_evaluation: false
choices:
- value: "...a generic  runner"
  checked: false
- value: "...a ruby framework for building runners"
  checked: true
- value: "...a library that you must use to build your runners"
  checked: false
