---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: 
manual_evaluation: false
choices:
- value: "...a Rails application"
  checked: false
- value: "...a docker image"
  checked: false
- value: "...a ruby gem"
  checked: true
